# Use the official Node.js image as a base
FROM node:lts-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json /app
RUN npm install

# Copy the rest of the application code
COPY . /app

# Expose the port the app will run on
EXPOSE 3000

# Command to run the app
CMD ["npm", "run", "start"]